// src/pages/MediaDetailPage.vue
<!-- src/pages/MediaDetailPage.vue -->
<template>
  <div v-if="isLoading" class="loading-container">
    <LoadingSpinner message="Loading media details..." />
  </div>

  <div v-else-if="errorMedia" class="error-container">
    <p>{{ errorMedia }}</p>
    <button @click="fetchMedia">Retry</button>
  </div>
  
  <div v-else-if="media" class="media-detail-page">
    <h2>{{ media.title }}</h2>
    <p><strong>Description:</strong> {{ media.description }}</p>
    <img :src="media.thumbnailUrl" :alt="media.title" class="media-image" />
    <p><strong>Uploaded:</strong> {{ new Date(media.createdAt).toLocaleString() }}</p>
    <p v-if="media.location"><strong>Location:</strong> {{ media.location }}</p>
    
    <section class="comments-section">
      <h3>Comments</h3>
      
      <div v-if="loadingComments" class="loading-container">
        <LoadingSpinner size="small" message="Loading comments..." />
      </div>
      <div v-else-if="errorComments" class="error-container">
        <p>{{ errorComments }}</p>
        <button @click="fetchComments">Retry</button>
      </div>
      
      <ul v-else-if="comments.length > 0" class="comment-list">
        <li v-for="comment in comments" :key="comment.id" class="comment-item">
          <p>{{ comment.text }}</p>
          <small>{{ new Date(comment.createdAt).toLocaleString() }}</small>
        </li>
      </ul>
      <p v-else>No comments yet.</p>

      <!-- Comment Form -->
      <form v-if="isAuthenticated" @submit.prevent="postComment" class="comment-form">
        <textarea v-model="newCommentText" placeholder="Add a comment..." required rows="3"></textarea>
        <div v-if="errorPostComment" class="error-container small">
          <p>{{ errorPostComment }}</p>
        </div>
        <button type="submit" :disabled="loadingPostComment">
          {{ loadingPostComment ? 'Posting...' : 'Post Comment' }}
        </button>
      </form>
    </section>
  </div>
  
  <div v-else>
    <p>Media not found.</p>
  </div>
</template>

<script setup>
import { ref, onMounted, computed } from 'vue';
import { useRoute } from 'vue-router';
import LoadingSpinner from '../components/LoadingSpinner.vue';

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL;
const route = useRoute();
const mediaId = route.params.id;

const media = ref(null);
const comments = ref([]);
const newCommentText = ref('');

const loadingMedia = ref(true);
const loadingComments = ref(true);
const loadingPostComment = ref(false);

const errorMedia = ref(null);
const errorComments = ref(null);
const errorPostComment = ref(null);

const isLoading = computed(() => loadingMedia.value);
const isAuthenticated = computed(() => !!localStorage.getItem('token'));

const fetchMedia = async () => {
  loadingMedia.value = true;
  errorMedia.value = null;
  try {
    const response = await fetch(`${API_BASE_URL}/media/${mediaId}`);
    if (!response.ok) throw new Error('Failed to load media.');
    media.value = await response.json();
  } catch (error) {
    errorMedia.value = error.message;
  } finally {
    loadingMedia.value = false;
  }
};

const fetchComments = async () => {
  loadingComments.value = true;
  errorComments.value = null;
  try {
    const response = await fetch(`${API_BASE_URL}/comments/${mediaId}`);
    if (!response.ok) throw new Error('Failed to load comments.');
    comments.value = await response.json();
  } catch (error) {
    errorComments.value = error.message;
  } finally {
    loadingComments.value = false;
  }
};

const postComment = async () => {
  if (!newCommentText.value.trim()) return;
  
  loadingPostComment.value = true;
  errorPostComment.value = null;
  const token = localStorage.getItem('token');

  try {
    const response = await fetch(`${API_BASE_URL}/comments`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`,
      },
      body: JSON.stringify({ mediaId, text: newCommentText.value }),
    });
    if (!response.ok) throw new Error('Failed to post comment.');
    
    const newComment = await response.json();
    comments.value.unshift(newComment); // Add to start of list
    newCommentText.value = ''; // Clear textarea
  } catch (error) {
    errorPostComment.value = error.message;
  } finally {
    loadingPostComment.value = false;
  }
};

onMounted(() => {
  fetchMedia();
  fetchComments();
});
</script>

<style scoped>
/* Add relevant styles for media detail page here */
.media-detail-page { max-width: 800px; margin: auto; }
.media-image { width: 100%; border-radius: 8px; }
.comments-section { margin-top: 40px; border-top: 1px solid #eee; padding-top: 20px; }
.comment-list { list-style: none; padding: 0; }
.comment-item { border-bottom: 1px solid #f0f0f0; padding-bottom: 10px; margin-bottom: 15px; }
.comment-form { margin-top: 20px; display: flex; flex-direction: column; gap: 10px; }
.error-container { color: #dc3545; text-align: center; margin: 20px; }
</style>

// src/pages/MediaDetailPage.tsx
import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import LoadingSpinner from '../components/LoadingSpinner';

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL;

type Media = {
  id: string;
  title: string;
  description: string;
  thumbnailUrl: string;
  createdAt: string;
  location?: string;
  coordinates?: {
    latitude: number;
    longitude: number;
  };
};

type Comment = {
  id: string;
  userId: string;
  text: string;
  createdAt: string;
};

const MediaDetailPage: React.FC = () => {
  const { id: mediaId } = useParams<{ id: string }>();
  const [media, setMedia] = useState<Media | null>(null);
  const [comments, setComments] = useState<Comment[]>([]);
  const [loadingMedia, setLoadingMedia] = useState<boolean>(true);
  const [loadingComments, setLoadingComments] = useState<boolean>(true);
  const [loadingPostComment, setLoadingPostComment] = useState<boolean>(false);
  const [errorMedia, setErrorMedia] = useState<string | null>(null);
  const [errorComments, setErrorComments] = useState<string | null>(null);
  const [errorPostComment, setErrorPostComment] = useState<string | null>(null);

  useEffect(() => {
    if (!mediaId) return;
  
    const fetchMedia = async () => {
      setLoadingMedia(true);
      setErrorMedia(null);
      try {
        const response = await fetch(`${API_BASE_URL}/media/${mediaId}`);
        if (!response.ok) throw new Error(`Error: ${response.status}`);
        const data: Media = await response.json();
        setMedia(data);
      } catch (error) {
        setErrorMedia('Failed to load media. Please try again.');
        console.error("Failed to fetch media:", error);
      } finally {
        setLoadingMedia(false);
      }
    };
  
    const fetchComments = async () => {
      setLoadingComments(true);
      setErrorComments(null);
      try {
        const response = await fetch(`${API_BASE_URL}/comments/${mediaId}`);
        if (!response.ok) throw new Error(`Error: ${response.status}`);
        const data: Comment[] = await response.json();
        setComments(data);
      } catch (error) {
        setErrorComments('Failed to load comments. Please try again.');
        console.error("Failed to fetch comments:", error);
      } finally {
        setLoadingComments(false);
      }
    };
  
    const retryFetchMedia = async () => {
      await fetchMedia();
    };
  
    const retryFetchComments = async () => {
      await fetchComments();
    };

    const retryPostComment = async (text: string) => {
      if (!mediaId) return;
      
      const token = localStorage.getItem('token');
      if (!token) return;

      setErrorPostComment(null);
      setLoadingPostComment(true);
      
      try {
        const response = await fetch(`${API_BASE_URL}/comments`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${token}`,
          },
          body: JSON.stringify({ mediaId, text }),
        });

        if (response.ok) {
          const newComment: Comment = await response.json();
          setComments((prev) => [newComment, ...prev]);
          setErrorPostComment(null);
        } else {
          throw new Error(`Error: ${response.status}`);
        }
      } catch (error) {
        setErrorPostComment('Failed to post comment. Please try again.');
        console.error('Error posting comment:', error);
      } finally {
        setLoadingPostComment(false);
      }
    };
  
    fetchMedia();
    fetchComments();

    // Make retry functions available to the component
    (window as any).retryFetchMedia = retryFetchMedia;
    (window as any).retryFetchComments = retryFetchComments;
    (window as any).retryPostComment = retryPostComment;
  }, [mediaId]);

  // Handle media fetch errors
  if (errorMedia) {
    return (
      <div style={{ textAlign: "center", margin: "40px 0" }}>
        <p style={{ color: "#dc3545", marginBottom: "10px" }}>{errorMedia}</p>
        <button
          onClick={() => (window as any).retryFetchMedia()}
          style={{
            backgroundColor: "#007bff",
            color: "white",
            border: "none",
            padding: "8px 16px",
            borderRadius: "4px",
            cursor: "pointer",
          }}
        >
          Retry
        </button>
      </div>
    );
  }
  
  // Handle comments fetch errors when media is loaded
  if (errorComments && media) {
    return (
      <div style={{ textAlign: "center", margin: "20px 0" }}>
        <p style={{ color: "#dc3545", marginBottom: "10px" }}>{errorComments}</p>
        <button
          onClick={() => (window as any).retryFetchComments()}
          style={{
            backgroundColor: "#007bff",
            color: "white",
            border: "none",
            padding: "8px 16px",
            borderRadius: "4px",
            cursor: "pointer",
          }}
        >
          Retry
        </button>
      </div>
    );
  }
  
  // Handle comment submission errors
  if (errorPostComment) {
    return (
      <div style={{
        margin: "20px auto",
        maxWidth: "500px",
        textAlign: "center",
        color: "#dc3545",
        padding: "15px",
        borderRadius: "4px",
        backgroundColor: "#f8d7da",
        border: "1px solid #f5c6cb",
      }}>
        <p style={{ margin: "0 0 10px 0" }}>{errorPostComment}</p>
        <button
          onClick={() => {
            const form = document.querySelector("form");
            const textarea = form?.elements.namedItem("commentText") as HTMLTextAreaElement;
            if (textarea?.value.trim()) {
              (window as any).retryPostComment(textarea.value.trim());
            }
          }}
          style={{
            backgroundColor: "#007bff",
            color: "white",
            border: "none",
            padding: "8px 16px",
            borderRadius: "4px",
            cursor: "pointer",
          }}
        >
          Retry
        </button>
      </div>
    );
  }

  const isLoading = loadingMedia || loadingComments;
  
  if (isLoading) {
    return <LoadingSpinner message="Loading media details..." />;
  }
  
  if (!media) {
    return <div>Media not found.</div>;
  }

  return (
    <div style={{ fontFamily: 'Arial, sans-serif', maxWidth: '800px', margin: '0 auto', padding: '20px' }}>
      <header style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px', borderBottom: '1px solid #eee', paddingBottom: '10px' }}>
        <h1>OSP Platform</h1>
        <nav>
          <a href="/" style={{ marginRight: '15px' }}>Home</a>
          <a href="/account-settings" style={{ marginRight: '15px' }}>Account</a>
          <button
            onClick={() => {
              localStorage.removeItem('token');
              window.location.href = '/';
            }}
            style={{ backgroundColor: '#dc3545', color: 'white', border: 'none', padding: '8px 12px', borderRadius: '4px', cursor: 'pointer' }}
          >
            Sign Out
          </button>
        </nav>
      </header>
      <main>
        <h2>{media.title}</h2>
        <p><strong>Description:</strong> {media.description}</p>
        <img
          src={media.thumbnailUrl}
          alt={media.title}
          style={{ width: '100%', maxHeight: '400px', objectFit: 'cover', borderRadius: '8px', marginBottom: '10px' }}
        />
        <p><strong>Uploaded:</strong> {new Date(media.createdAt).toLocaleString()}</p>
        {media.location && <p><strong>Location:</strong> {media.location}</p>}
        {media.coordinates && (
          <p>
            <strong>Coordinates:</strong> {media.coordinates.latitude}, {media.coordinates.longitude}
          </p>
        )}
      </main>

      <section style={{ marginTop: '40px', borderTop: '1px solid #eee', paddingTop: '20px' }}>
        <h3>Comments</h3>
        {comments.length === 0 ? (
          <p>No comments yet.</p>
        ) : (
          <ul style={{ listStyle: 'none', padding: 0 }}>
            {comments.map((comment) => (
              <li key={comment.id} style={{ marginBottom: '15px', paddingBottom: '10px', borderBottom: '1px solid #f0f0f0' }}>
                <p style={{ margin: '5px 0', whiteSpace: 'pre-wrap' }}>{comment.text}</p>
                <small style={{ color: '#888' }}>
                  {new Date(comment.createdAt).toLocaleString()}
                </small>
              </li>
            ))}
          </ul>
        )}

        {/* Comment Form - Only shown if user is authenticated */}
        {localStorage.getItem('token') && (
          <form
            onSubmit={async (e) => {
              e.preventDefault();
              const form = e.target as HTMLFormElement;
              const textarea = form.elements.namedItem('commentText') as HTMLTextAreaElement;
              const text = textarea.value.trim();
              if (!text || !mediaId) return;

              const token = localStorage.getItem('token');
              if (!token) return;

              setErrorPostComment(null);
              
              try {
                const response = await fetch('/api/v1/comments', {
                  method: 'POST',
                  headers: {
                    'Content-Type': 'application/json',
                    Authorization: `Bearer ${token}`,
                  },
                  body: JSON.stringify({ mediaId, text }),
                });

                if (response.ok) {
                  const newComment: Comment = await response.json();
                  setComments((prev) => [newComment, ...prev]);
                  textarea.value = '';
                  setErrorPostComment(null);
                } else {
                  throw new Error(`Error: ${response.status}`);
                }
              } catch (error) {
                const errorMsg = 'Failed to post comment. Please try again.';
                setErrorPostComment(errorMsg);
                console.error('Error posting comment:', error);
              }
            }}
            style={{
              marginTop: '20px',
              display: 'flex',
              flexDirection: 'column',
              gap: '10px',
            }}
          >
            <textarea
              name="commentText"
              placeholder="Add a comment..."
              required
              rows={3}
              style={{
                padding: '10px',
                borderRadius: '4px',
                border: '1px solid #ccc',
                resize: 'vertical',
              }}
            />
            <button
              type="submit"
              style={{
                backgroundColor: '#007bff',
                color: 'white',
                border: 'none',
                padding: '10px 16px',
                borderRadius: '4px',
                cursor: 'pointer',
                alignSelf: 'flex-start',
              }}
            >
              Post Comment
            </button>
          </form>
        )}
      </section>
    </div>
  );
};

export default MediaDetailPage;
